url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Frances Bryson"
description: "Robotics PhD Candidate at Georgia Institute of Technology"
markdown: GFM
