menu:
- {name: 'research', url: '/research'}
- {name: 'cv', url: '/cv'}
- {name: 'publications', url: '/publications'}
- {name: 'contact', url: '/contact'}
- {name: 'additional', url: '/misc'}

research:
- {name: 'Icefin', image: 'assets/img/icefin.jpg', url: 'icefin'}
- {name: 'Vertical Entry Robot for Navigating Europa',  image: 'assets/img/verne_logo.jpg', url: 'verne'}
- {name: 'Minature Robotic Electrodialysis', image: 'assets/img/mred.jpg', url: 'mred'}
- {name: 'Small-Scale Tether Management for Ocean Profiling', image: 'assets/img/tms.jpg', url: 'tms'}
- {name: 'Robotic Solid Sampling for ROVs/AUVs', image: 'assets/img/arm.jpg', url: 'arm'}

courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/fbryson820'}
- {icon: 'github', link: 'https://github.gatech.edu/fbryson7'}
- {icon: 'instagram', link: 'https://instagram.com/francesb45'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/frances-bryson/'}

contacts:
- {name: 'Frances Bryson', title: 'Graduate Research Assistant', department: 'Mechanical Engineering and Earth and Atmospheric Sciences', institution: 'Georgia Institute of Technology', institution_address: '311 Ferst Dr NW, Atlanta, GA 3033', email: 'fbryson7@gatech.edu', image: 'assets/img/contact.jpg'}
